### ISSUE TITLE
Include Monarch in the Chaos Toolkit Extensions page 

### ISSUE THREAD

**Issue by mperrien** [tmobile/monarch#2]
Hello,

I would like to include Monarch on this page of the Chaos Toolkit website:
https://chaostoolkit.org/extensions

Would it be OK with you?

Thanks.

**Comment by Eadword** [comment]
We would love this!

Internally we are working on a complete rewrite of Monarch that will fundamentally change how it works and what it's capable of. To minimize confusion when we introduce new code and eventually change over master in this repo, it would be best if *this* is referred to as `monarch-cli` and all links are to the branch I just created of the same name (https://github.com/tmobile/monarch/tree/monarch-cli).

**Comment by mperrien** [comment]
Thanks for you quick response, Matthew, I'll be doing just that.

We'd also like to write an article about Monarch (to be published on the (forthcoming) Chaos Toolkit blog (or maybe on Medium). Would you be up for an interview with us?

**Comment by mperrien** [comment]
Here it is : https://chaostoolkit.org/extensions/monarch-cli
